#!/opt/anaconda/bin/python

import sys
reload(sys)
sys.setdefaultencoding('utf8')
import os
import io
import shutil
import atexit
from nbconvert.preprocessors import ExecutePreprocessor, CellExecutionError
import nbformat as nbf
import uuid
import ast

sys.path.append('/opt/anaconda/bin/')
import cioppy
ciop = cioppy.Cioppy()

# define the exit codes
SUCCESS = 0
ERR_NB_RUNTIME=10

references = []

# add a trap to exit gracefully
def clean_exit(exit_code):
    log_level = 'INFO'
    if exit_code != SUCCESS:
        log_level = 'ERROR'  
   
    msg = {SUCCESS: 'Processing successfully concluded',
           ERR_NB_RUNTIME: 'Failed to run notebook'
    }
 
    ciop.log(log_level, msg[exit_code])  


# def parametrize(reference):

#     global nb
        
#     ts = ciop.getparam('ts')
#     nc = ciop.getparam('nc')
#     maxit = ciop.getparam('maxit')
    
#     nb.cells[0]['source'] = 's3_url = "%s"' % ( reference ) 
#     nb.cells[8]['source'] = 'ts = %s' % (ts)  
#     nb.cells[10]['source'] = 'nc = %s' % (nc)
#     nb.cells[12]['source'] = 'maxit = %s' % (maxit)  



def parametrize(reference):
    
    global nb
    
    for index, cell in enumerate(nb['cells']):
       
        if str(cell['cell_type']) == 'code': 
        
            try:
                root_ast = ast.parse(str(cell['source']))
                names = list({node.id for node in ast.walk(root_ast) if isinstance(node, ast.Name)})
                
                if len(names) == 1:
                    
                    if names[0] == 'data_path':
                        ciop.log('INFO', 'cell %s updated with \'data_path\' value %s' % (index, tmp_dir))
                        cell['source'] = 'data_path = \'%s\'' % tmp_dir  
        
                    if names[0] == 'input_identifier':
                        ciop.log('INFO', 'cell %s updated with \'input_identifier\' value %s' % (index, identifier))
                        cell['source'] = 'input_identifier = \'%s\'' % identifier  
                
                    if names[0] == 'input_reference':
                        ciop.log('INFO', 'cell %s updated with \'input_reference\' value %s' % (index, reference))
                        cell['source'] = 'input_reference = \'%s\'' % reference  
                
                if len(names) != 2:
                    continue
                
                if names[0] == 'dict' or names[1] == 'dict':
                    
                    # deal with the alphabetical order
                    if names[1] == 'dict': 
                        names[1] = names[0]
                        names[0] = 'dict'
                
                    exec(str(cell['source'])) in globals(), locals()
                
                    if names[0] == 'dict' and 'title' in eval(names[1]).keys() and 'abstract' in eval(names[1]).keys() and 'id' in eval(names[1]).keys() and 'value' in eval(names[1]).keys():
                                      
                        eval(names[1])['value'] = ciop.getparam(eval(names[1])['id'])
    
                        new_source = 'dict(['

                        for i, keys in enumerate(eval(names[1])):
                            if i == 0: 
                                new_source = new_source + '( "%s", "%s")' % (keys, eval(names[1])[keys]) 
                            else:
                                new_source = new_source + ',( "%s", "%s")' % (keys, eval(names[1])[keys]) 
        
                        new_source = new_source + '])'
    
                        cell['source'] = '%s = %s' % (names[1], new_source)
         
                        ciop.log('INFO', 'cell %s %s updated' % (index, names[1]))
                    
            except SyntaxError:
                
                continue



def execute(reference, nb_source, nb_target, kernel = 'python2'):
    
    global nb
   
    nb = nbf.read(nb_source, 4)
    
    ciop.log('INFO', 'Execute notebook')
    
    parametrize(reference)
    
    # execute the notebook
    ep = ExecutePreprocessor(timeout=None, kernel_name=kernel)

    try:
      out = ep.preprocess(nb, {'metadata': {'path': './'}})
    except CellExecutionError:
      out = None
      ciop.log('ERROR', 'Error executing the notebook "%s".' % nb_source)

      with io.open(nb_target, 'wb') as file:
        file.write(nbf.writes(nb))
        file.close()
      
      ciop.publish(nb_target, metalink=True)
      raise
    finally:
      ciop.log('INFO', 'Write notebook')  
      with io.open(nb_target, 'wb') as file:
        file.write(nbf.writes(nb))
        file.close() 

def publish(runtime):
   
    # publish
    ciop.log('INFO', 'Publishing ') 
    ciop.publish(runtime, metalink=True, recursive=True)

def clean_up(runtime):
           
    # clean-up 
    shutil.rmtree(runtime)

def main():

    # create the folder for the data stage-in
    global tmp_dir
    tmp_dir = os.path.join('/tmp', 'workspace-' + str(uuid.uuid4()), 'data') 
    os.makedirs(tmp_dir)

    # Loops over all the inputs
    for reference in sys.stdin:
      references.append(reference.rstrip())

    for reference in references:
                    
      runtime = os.path.join(ciop.tmp_dir, str(uuid.uuid4()))    

      os.makedirs(runtime)
      os.chdir(runtime)
    
      # execute the notebook
      nb_source = os.path.join('/application', 'notebook', 'libexec', 'input.ipynb')
      nb_target = os.path.join(runtime, 'result.ipynb')  
      execute(reference, nb_source, nb_target, 'python2')  
    
      # publish
      publish(runtime)   
   
      # clean-up 
      clean_up(runtime)

try:
  main()
except SystemExit as e:
  if e.args[0]:
    clean_exit(e.args[0])
  raise
else:
  atexit.register(clean_exit, 0)


